### ISSUE TITLE
Time seems inaccurate 

### ISSUE THREAD

**Issue by obrowny** [benjamintd/attestation.page#3]
If time is 12:00, attestation will be 11:00. There is a problem with local time zone.
Would it be possible to have a «time blank » version as well ?

**Comment by obrowny** [comment]
Well, works on the phone but not on my computer so the problem may be on my machine. Sorry.

**Comment by benjamintd** [comment]
@obrowny I'm taking the current time of the device, which may be inaccurate with daylight savings (or if your location is set to somewhere outside the actual timezone). 

That said, I should probably make this field editable. Thanks for contributing !

**Comment by benjamintd** [comment]
I'm closing in favor of #4
