### ISSUE TITLE
L'heure de sortie n'est pas mise à jour lorsque l'on revient sur le générateur.

### ISSUE THREAD

**Issue by backandio** [benjamintd/attestation.page#7]
Bonjour, et bravo c'est très pratique.

Mais hier je suis sortit avec une attestation avec la mauvaise heure (sans conséquence).

Reproduire :  (Android 10, Chrome)

- Comme suggéré par l'outil, créer un raccourci sur l'accueil
- Lancer le raccourci et le remplir, générer une attestation.
- Plus tard, revenir, relancer le raccourci. L'heure est resté à l'heure précédante. Cliquer sur un des boutons bleu génère une attestation à l'ancienne heure.

A mon avis, il faudrait détecter que la page est revenu au premier plan (je ne sais pas si possible dans Chrome)
Le plus rapide serait peut etre, sur le clic d'un des boutons bleu, de prendre l'heure à ce moment là.
Sinon bien afficher l'heure en haut des boutons pour au moins constater le souci et rafraichir la page (ce qui remet à l'heure).

Je me permet de remonter ça car ca peut couter 135 euros :)

**Comment by cyfax** [comment]
@backandio  Il faut faire un [reload](https://browserhow.com/how-to-do-hard-refresh-and-reload-webpage-in-chrome-android/) de la page pour rafraichir la date et l'heure.
